name: calculadora_agrocarbon
description: Calculadora de carbono orgÃ¢nico do solo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  flutter_modular: ^6.3.4
  animations: ^2.0.11
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.12.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/screenshots/


  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/agrocarbon_logo_reduced.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/agrocarbon_logo_reduced.png"
