name: calculadora_agrocarbon
description: Calculadora de carbono orgÃ¢nico do solo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  flutter_modular: ^6.3.4
  google_fonts: ^6.2.1
  animations: ^2.0.11
  confetti: ^0.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
